"""Crear modelo inicial

Revision ID: 34ba5ad163c9
Revises: 
Create Date: 2026-08-18 16:55:23.027812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ba5ad163c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inmueble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=False),
    sa.Column('codigo_facturacion', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('codigo_postal', sa.Text(), nullable=True),
    sa.Column('poblacion', sa.Text(), nullable=False),
    sa.Column('provincia', sa.Text(), nullable=False),
    sa.Column('ref_catastral', sa.Text(), nullable=True),
    sa.Column('seguro', sa.Text(), nullable=True),
    sa.Column('participacion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('participacion > 0 AND participacion <= 10000', name='ck_inmueble_participacion'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_facturacion'),
    sa.UniqueConstraint('referencia')
    )
    op.create_table('inquilino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('nif', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('codigo_postal', sa.Text(), nullable=True),
    sa.Column('poblacion', sa.Text(), nullable=True),
    sa.Column('provincia', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('fecha_inicio_facturacion', sa.Date(), nullable=False),
    sa.Column('fianza', sa.Integer(), nullable=False),
    sa.Column('iva_porcentaje', sa.Integer(), nullable=False),
    sa.Column('retencion_porcentaje', sa.Integer(), nullable=False),
    sa.Column('direccion_facturacion', sa.Text(), nullable=False),
    sa.Column('codigo_postal_facturacion', sa.Text(), nullable=True),
    sa.Column('poblacion_facturacion', sa.Text(), nullable=False),
    sa.Column('provincia_facturacion', sa.Text(), nullable=False),
    sa.Column('concepto_factura', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='ck_contrato_fecha_fin'),
    sa.CheckConstraint('fecha_inicio_facturacion >= fecha_inicio', name='ck_contrato_fecha_inicio_facturacion'),
    sa.CheckConstraint('fecha_vencimiento >= fecha_inicio', name='ck_contrato_fecha_vencimiento'),
    sa.CheckConstraint('fianza >= 0', name='ck_contrato_fianza'),
    sa.CheckConstraint('iva_porcentaje >= 0', name='ck_contrato_iva'),
    sa.CheckConstraint('retencion_porcentaje >= 0', name='ck_contrato_retencion'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ajuste_renta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo IN ('REDUCCION_PORCENTUAL', 'REDUCCION_FIJA', 'IMPORTE_FIJO')", name='ck_ajuste_renta_tipo'),
    sa.CheckConstraint('fecha_hasta >= fecha_desde', name='ck_ajuste_renta_fechas'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_inquilino',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.CheckConstraint('orden > 0', name='ck_contrato_inquilino_orden'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contrato_id', 'inquilino_id'),
    sa.UniqueConstraint('contrato_id', 'orden', name='uq_contrato_inquilino_orden')
    )
    op.create_table('renta_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('importe >= 0', name='ck_renta_contrato_importe'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'fecha_desde', name='uq_renta_contrato_fecha_desde')
    )
    op.create_table('revision_renta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prevista', sa.Date(), nullable=False),
    sa.Column('metodo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('porcentaje_aplicado', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'APLICADA', 'NO_APLICADA')", name='ck_revision_renta_estado'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'fecha_prevista', name='uq_revision_renta_fecha_prevista')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revision_renta')
    op.drop_table('renta_contrato')
    op.drop_table('contrato_inquilino')
    op.drop_table('ajuste_renta')
    op.drop_table('contrato')
    op.drop_table('inquilino')
    op.drop_table('inmueble')
    # ### end Alembic commands ###
