"""2026-10-08 DistribucionApunte

Revision ID: 3a6b0c3f2ed1
Revises: ed577885e44a
Create Date: 2026-10-08 13:29:43.592758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3a6b0c3f2ed1'
down_revision: Union[str, Sequence[str], None] = 'ed577885e44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Crea la distribución persistente de apuntes entre locales."""

    op.create_table(
        "distribucion_apunte",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apunte_id", sa.Integer(), nullable=False),
        sa.Column("inmueble_id", sa.Integer(), nullable=False),
        sa.Column("participacion", sa.Integer(), nullable=False),
        sa.Column("base", sa.Integer(), nullable=False),
        sa.Column("iva_importe", sa.Integer(), nullable=False),
        sa.Column("retencion_importe", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "base >= 0",
            name="ck_distribucion_apunte_base",
        ),
        sa.CheckConstraint(
            "iva_importe >= 0",
            name="ck_distribucion_apunte_iva",
        ),
        sa.CheckConstraint(
            "participacion > 0 AND participacion <= 10000",
            name="ck_distribucion_apunte_participacion",
        ),
        sa.CheckConstraint(
            "retencion_importe >= 0",
            name="ck_distribucion_apunte_retencion",
        ),
        sa.CheckConstraint(
            "total = base + iva_importe - retencion_importe",
            name="ck_distribucion_apunte_total_coherente",
        ),
        sa.CheckConstraint(
            "total >= 0",
            name="ck_distribucion_apunte_total",
        ),
        sa.ForeignKeyConstraint(
            ["apunte_id"],
            ["apunte_contable.id"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["inmueble_id"],
            ["inmueble.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "apunte_id",
            "inmueble_id",
            name="uq_distribucion_apunte_inmueble",
        ),
    )


def downgrade() -> None:
    """Elimina la distribución persistente de apuntes."""

    op.drop_table("distribucion_apunte")

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distribucion_apunte')
    # ### end Alembic commands ###
