"""Añadir apuntes y movimientos previstos

Revision ID: a34a1fa7fe25
Revises: bec8b4e68350
Create Date: 2026-08-28 16:25:05.935888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'a34a1fa7fe25'
down_revision: Union[str, Sequence[str], None] = 'bec8b4e68350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apunte_contable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('naturaleza', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('subcategoria', sa.Text(), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('base', sa.Integer(), nullable=False),
    sa.Column('iva_importe', sa.Integer(), nullable=False),
    sa.Column('retencion_importe', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('tercero_nombre', sa.Text(), nullable=False),
    sa.Column('tercero_nif', sa.Text(), nullable=False),
    sa.Column('referencia_documento', sa.Text(), nullable=False),
    sa.Column('ruta_documento', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("naturaleza IN ('INGRESO', 'GASTO')", name='ck_apunte_contable_naturaleza'),
    sa.CheckConstraint('base >= 0', name='ck_apunte_contable_base'),
    sa.CheckConstraint('iva_importe >= 0', name='ck_apunte_contable_iva'),
    sa.CheckConstraint('retencion_importe >= 0', name='ck_apunte_contable_retencion'),
    sa.CheckConstraint('total >= 0', name='ck_apunte_contable_total'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento_previsto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('apunte_id', sa.Integer(), nullable=True),
    sa.Column('fecha_prevista', sa.Date(), nullable=False),
    sa.Column('naturaleza', sa.Text(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('importe_esperado', sa.Integer(), nullable=False),
    sa.Column('contraparte', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'CONCILIADO')", name='ck_movimiento_previsto_estado'),
    sa.CheckConstraint("naturaleza IN ('INGRESO', 'GASTO')", name='ck_movimiento_previsto_naturaleza'),
    sa.CheckConstraint('importe_esperado >= 0', name='ck_movimiento_previsto_importe'),
    sa.ForeignKeyConstraint(['apunte_id'], ['apunte_contable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        "inmueble",
        sa.Column(
            "ruta_documentos",
            sa.Text(),
            nullable=False,
            server_default="",
        ),
    )

    with op.batch_alter_table(
        "factura_linea",
    ) as batch_op:
        batch_op.drop_constraint(
            "ck_factura_linea_tipo",
            type_="check",
        )

        batch_op.create_check_constraint(
            "ck_factura_linea_tipo",
            "tipo IN ("
            "'RENTA', "
            "'DIFERENCIA_REVISION', "
            "'REPERCUSION_GASTO', "
            "'OTRO'"
            ")",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table(
        "factura_linea",
    ) as batch_op:
        batch_op.drop_constraint(
            "ck_factura_linea_tipo",
            type_="check",
        )

        batch_op.create_check_constraint(
            "ck_factura_linea_tipo",
            "tipo IN ("
            "'RENTA', "
            "'DIFERENCIA_REVISION', "
            "'REPERCUSION_GASTO'"
            ")",
        )

    op.drop_column(
        "inmueble",
        "ruta_documentos",
    )

    op.drop_table(
        "movimiento_previsto",
    )

    op.drop_table(
        "apunte_contable",
    )
    # ### end Alembic commands ###
