"""crear-tabla-conciliacion

Revision ID: c83a4c231453
Revises: 0ae6f256cd56
Create Date: 2026-09-13 17:30:10.435963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c83a4c231453'
down_revision: Union[str, Sequence[str], None] = '0ae6f256cd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conciliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_bancario_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_previsto_id', sa.Integer(), nullable=False),
    sa.Column('importe_asociado', sa.Integer(), nullable=False),
    sa.CheckConstraint('importe_asociado > 0', name='ck_conciliacion_importe_positivo'),
    sa.ForeignKeyConstraint(['movimiento_bancario_id'], ['movimiento_bancario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimiento_previsto_id'], ['movimiento_previsto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_bancario_id', 'movimiento_previsto_id', name='uq_conciliacion_movimientos')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conciliacion')
    # ### end Alembic commands ###
