"""Añadir MovimientosBancarios

Revision ID: ccfe6d430eda
Revises: 8ee51ae4946d
Create Date: 2026-09-11 11:55:05.528085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ccfe6d430eda'
down_revision: Union[str, Sequence[str], None] = '8ee51ae4946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimiento_bancario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('naturaleza', sa.Text(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.Column('tipo_original', sa.Text(), nullable=False),
    sa.Column('descripcion_original', sa.Text(), nullable=False),
    sa.Column('referencia_bancaria', sa.Text(), nullable=False),
    sa.Column('huella_importacion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'CONCILIADO', 'DESCARTADO')", name='ck_movimiento_bancario_estado'),
    sa.CheckConstraint("naturaleza IN ('INGRESO', 'GASTO')", name='ck_movimiento_bancario_naturaleza'),
    sa.CheckConstraint('importe > 0', name='ck_movimiento_bancario_importe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('huella_importacion', name='uq_movimiento_bancario_huella')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimiento_bancario')
    # ### end Alembic commands ###
