"""Crear esquema inicial

Revision ID: d8069a13ec24
Revises: 
Create Date: 2026-10-10 18:59:15.182862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd8069a13ec24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inmueble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_padre_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('referencia', sa.Text(), nullable=False),
    sa.Column('codigo_facturacion', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('codigo_postal', sa.Text(), nullable=True),
    sa.Column('poblacion', sa.Text(), nullable=False),
    sa.Column('provincia', sa.Text(), nullable=False),
    sa.Column('ref_catastral', sa.Text(), nullable=True),
    sa.Column('seguro', sa.Text(), nullable=True),
    sa.Column('ruta_documentos', sa.Text(), nullable=False),
    sa.Column('participacion', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo != 'T' OR (inmueble_padre_id IS NULL AND participacion = 10000)", name='ck_inmueble_total'),
    sa.CheckConstraint("tipo IN ('T', 'P', 'L', 'G')", name='ck_inmueble_tipo'),
    sa.CheckConstraint('inmueble_padre_id IS NULL OR inmueble_padre_id != id', name='ck_inmueble_no_es_su_padre'),
    sa.CheckConstraint('participacion > 0 AND participacion <= 10000', name='ck_inmueble_participacion'),
    sa.ForeignKeyConstraint(['inmueble_padre_id'], ['inmueble.id'], name='fk_inmueble_padre', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_facturacion'),
    sa.UniqueConstraint('referencia')
    )
    op.create_table('inquilino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('nif', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('codigo_postal', sa.Text(), nullable=True),
    sa.Column('poblacion', sa.Text(), nullable=True),
    sa.Column('provincia', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telefono', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('movimiento_bancario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('naturaleza', sa.Text(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.Column('tipo_original', sa.Text(), nullable=False),
    sa.Column('descripcion_original', sa.Text(), nullable=False),
    sa.Column('referencia_bancaria', sa.Text(), nullable=False),
    sa.Column('huella_importacion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'CONCILIADO', 'DESCARTADO')", name='ck_movimiento_bancario_estado'),
    sa.CheckConstraint("naturaleza IN ('INGRESO', 'GASTO')", name='ck_movimiento_bancario_naturaleza'),
    sa.CheckConstraint('importe > 0', name='ck_movimiento_bancario_importe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('huella_importacion', name='uq_movimiento_bancario_huella')
    )
    op.create_table('apunte_contable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('naturaleza', sa.Text(), nullable=False),
    sa.Column('categoria', sa.Text(), nullable=False),
    sa.Column('subcategoria', sa.Text(), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.Column('criterio_periodo', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=False),
    sa.Column('nombre_documento', sa.Text(), nullable=False),
    sa.Column('base', sa.Integer(), nullable=False),
    sa.Column('iva_importe', sa.Integer(), nullable=False),
    sa.Column('retencion_importe', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('tercero_nombre', sa.Text(), nullable=False),
    sa.Column('tercero_nif', sa.Text(), nullable=False),
    sa.Column('referencia_documento', sa.Text(), nullable=False),
    sa.Column('ruta_documento', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            (\n                periodo_desde IS NULL\n                AND periodo_hasta IS NULL\n                AND criterio_periodo IS NULL\n            )\n            OR\n            (\n                periodo_desde IS NOT NULL\n                AND periodo_hasta IS NOT NULL\n                AND criterio_periodo IS NOT NULL\n                AND criterio_periodo IN (\n                    'EXCLUIR_HASTA',\n                    'EXCLUIR_DESDE',\n                    'INCLUIR_AMBOS',\n                    'EXCLUIR_AMBOS'\n                )\n            )\n            ", name='ck_apunte_contable_criterio_periodo'),
    sa.CheckConstraint("\n            tratamiento IN (\n                'CONTABILIZAR',\n                'REPERCUTIR',\n                'FACTURAR'\n            )\n            ", name='ck_apunte_contable_tratamiento'),
    sa.CheckConstraint("naturaleza IN ('INGRESO', 'GASTO')", name='ck_apunte_contable_naturaleza'),
    sa.CheckConstraint('\n            (\n                periodo_desde IS NULL\n                AND periodo_hasta IS NULL\n            )\n            OR\n            (\n                periodo_desde IS NOT NULL\n                AND periodo_hasta IS NOT NULL\n            )\n            ', name='ck_apunte_contable_periodo_completo'),
    sa.CheckConstraint('\n            periodo_desde IS NULL\n            OR periodo_hasta >= periodo_desde\n            ', name='ck_apunte_contable_periodo_orden'),
    sa.CheckConstraint('base >= 0', name='ck_apunte_contable_base'),
    sa.CheckConstraint('iva_importe >= 0', name='ck_apunte_contable_iva'),
    sa.CheckConstraint('retencion_importe >= 0', name='ck_apunte_contable_retencion'),
    sa.CheckConstraint('total >= 0', name='ck_apunte_contable_total'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('genera_factura', sa.Boolean(), nullable=False),
    sa.Column('fecha_inicio_facturacion', sa.Date(), nullable=False),
    sa.Column('fianza', sa.Integer(), nullable=False),
    sa.Column('iva_porcentaje', sa.Integer(), nullable=False),
    sa.Column('retencion_porcentaje', sa.Integer(), nullable=False),
    sa.Column('direccion_facturacion', sa.Text(), nullable=False),
    sa.Column('codigo_postal_facturacion', sa.Text(), nullable=True),
    sa.Column('poblacion_facturacion', sa.Text(), nullable=False),
    sa.Column('provincia_facturacion', sa.Text(), nullable=False),
    sa.Column('concepto_factura', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('fecha_fin IS NULL OR fecha_fin >= fecha_inicio', name='ck_contrato_fecha_fin'),
    sa.CheckConstraint('fecha_inicio_facturacion >= fecha_inicio', name='ck_contrato_fecha_inicio_facturacion'),
    sa.CheckConstraint('fecha_vencimiento >= fecha_inicio', name='ck_contrato_fecha_vencimiento'),
    sa.CheckConstraint('fianza >= 0', name='ck_contrato_fianza'),
    sa.CheckConstraint('iva_porcentaje >= 0', name='ck_contrato_iva'),
    sa.CheckConstraint('retencion_porcentaje >= 0', name='ck_contrato_retencion'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anexo_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('nueva_fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=True),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.CheckConstraint("(tipo = 'CARENCIA' AND fecha_desde IS NOT NULL AND fecha_hasta IS NOT NULL) OR (tipo != 'CARENCIA' AND fecha_desde IS NULL AND fecha_hasta IS NULL)", name='ck_anexo_contrato_carencia_fechas'),
    sa.CheckConstraint("tipo IN ('CAMBIO_RENTA', 'PRORROGA', 'CARENCIA')", name='ck_anexo_contrato_tipo'),
    sa.CheckConstraint('fecha_hasta IS NULL OR fecha_desde IS NULL OR fecha_hasta >= fecha_desde', name='ck_anexo_contrato_periodo'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contrato_inquilino',
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.CheckConstraint('orden > 0', name='ck_contrato_inquilino_orden'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('contrato_id', 'inquilino_id'),
    sa.UniqueConstraint('contrato_id', 'orden', name='uq_contrato_inquilino_orden')
    )
    op.create_table('distribucion_apunte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apunte_id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('participacion', sa.Integer(), nullable=False),
    sa.Column('base', sa.Integer(), nullable=False),
    sa.Column('iva_importe', sa.Integer(), nullable=False),
    sa.Column('retencion_importe', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.CheckConstraint('base >= 0', name='ck_distribucion_apunte_base'),
    sa.CheckConstraint('iva_importe >= 0', name='ck_distribucion_apunte_iva'),
    sa.CheckConstraint('participacion > 0 AND participacion <= 10000', name='ck_distribucion_apunte_participacion'),
    sa.CheckConstraint('retencion_importe >= 0', name='ck_distribucion_apunte_retencion'),
    sa.CheckConstraint('total = base + iva_importe - retencion_importe', name='ck_distribucion_apunte_total_coherente'),
    sa.CheckConstraint('total >= 0', name='ck_distribucion_apunte_total'),
    sa.ForeignKeyConstraint(['apunte_id'], ['apunte_contable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apunte_id', 'inmueble_id', name='uq_distribucion_apunte_inmueble')
    )
    op.create_table('movimiento_previsto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inmueble_id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=True),
    sa.Column('apunte_id', sa.Integer(), nullable=True),
    sa.Column('fecha_prevista_desde', sa.Date(), nullable=True),
    sa.Column('fecha_prevista_hasta', sa.Date(), nullable=True),
    sa.Column('naturaleza', sa.Text(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('importe_esperado', sa.Integer(), nullable=False),
    sa.Column('contraparte', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('metodo_conciliacion', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            metodo_conciliacion IS NULL\n            OR metodo_conciliacion IN ('INDIVIDUAL', 'MANUAL')\n            ", name='ck_movimiento_previsto_metodo_conciliacion'),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'PARCIAL', 'CONCILIADO', 'CANCELADO')", name='ck_movimiento_previsto_estado'),
    sa.CheckConstraint("naturaleza IN ('INGRESO', 'GASTO')", name='ck_movimiento_previsto_naturaleza'),
    sa.CheckConstraint('\n            fecha_prevista_desde IS NULL\n            OR fecha_prevista_hasta IS NULL\n            OR fecha_prevista_hasta >= fecha_prevista_desde\n            ', name='ck_movimiento_previsto_fechas_orden'),
    sa.CheckConstraint('\n            fecha_prevista_hasta IS NULL\n            OR fecha_prevista_desde IS NOT NULL\n            ', name='ck_movimiento_previsto_fechas_completas'),
    sa.CheckConstraint('importe_esperado > 0', name='ck_movimiento_previsto_importe'),
    sa.ForeignKeyConstraint(['apunte_id'], ['apunte_contable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inmueble_id'], ['inmueble.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_renta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prevista', sa.Date(), nullable=False),
    sa.Column('metodo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('porcentaje_aplicado', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('PENDIENTE', 'APLICADA', 'NO_APLICADA')", name='ck_revision_renta_estado'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'fecha_prevista', name='uq_revision_renta_fecha_prevista')
    )
    op.create_table('ajuste_renta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('anexo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo IN ('REDUCCION_PORCENTUAL', 'REDUCCION_FIJA', 'IMPORTE_FIJO')", name='ck_ajuste_renta_tipo'),
    sa.CheckConstraint('fecha_hasta >= fecha_desde', name='ck_ajuste_renta_fechas'),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexo_contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conciliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_bancario_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_previsto_id', sa.Integer(), nullable=False),
    sa.Column('importe_asociado', sa.Integer(), nullable=False),
    sa.CheckConstraint('importe_asociado > 0', name='ck_conciliacion_importe_positivo'),
    sa.ForeignKeyConstraint(['movimiento_bancario_id'], ['movimiento_bancario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movimiento_previsto_id'], ['movimiento_previsto.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movimiento_bancario_id', 'movimiento_previsto_id', name='uq_conciliacion_movimientos')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero_secuencia', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.Text(), nullable=False),
    sa.Column('referencia_inmueble', sa.Text(), nullable=False),
    sa.Column('descripcion_inmueble', sa.Text(), nullable=False),
    sa.Column('direccion_facturacion', sa.Text(), nullable=False),
    sa.Column('codigo_postal_facturacion', sa.Text(), nullable=True),
    sa.Column('poblacion_facturacion', sa.Text(), nullable=False),
    sa.Column('provincia_facturacion', sa.Text(), nullable=False),
    sa.Column('apunte_contable_id', sa.Integer(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('base', sa.Integer(), nullable=False),
    sa.Column('iva_porcentaje', sa.Integer(), nullable=False),
    sa.Column('iva_importe', sa.Integer(), nullable=False),
    sa.Column('retencion_porcentaje', sa.Integer(), nullable=False),
    sa.Column('retencion_importe', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('revision_renta_id', sa.Integer(), nullable=True),
    sa.Column('aviso_revision', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('ruta_pdf', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('EMITIDA', 'ANULADA')", name='ck_factura_estado'),
    sa.CheckConstraint('anio > 0', name='ck_factura_anio'),
    sa.CheckConstraint('base >= 0', name='ck_factura_base'),
    sa.CheckConstraint('iva_importe >= 0', name='ck_factura_iva_importe'),
    sa.CheckConstraint('iva_porcentaje >= 0', name='ck_factura_iva_porcentaje'),
    sa.CheckConstraint('numero_secuencia > 0', name='ck_factura_numero_secuencia'),
    sa.CheckConstraint('retencion_importe >= 0', name='ck_factura_retencion_importe'),
    sa.CheckConstraint('retencion_porcentaje >= 0', name='ck_factura_retencion_porcentaje'),
    sa.CheckConstraint('total >= 0', name='ck_factura_total'),
    sa.ForeignKeyConstraint(['apunte_contable_id'], ['apunte_contable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_renta_id'], ['revision_renta.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apunte_contable_id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('imputacion_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apunte_id', sa.Integer(), nullable=True),
    sa.Column('distribucion_apunte_id', sa.Integer(), nullable=True),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.CheckConstraint('\n            (\n                apunte_id IS NOT NULL\n                AND distribucion_apunte_id IS NULL\n            )\n            OR\n            (\n                apunte_id IS NULL\n                AND distribucion_apunte_id IS NOT NULL\n            )\n            ', name='ck_imputacion_contrato_origen'),
    sa.CheckConstraint('importe > 0', name='ck_imputacion_contrato_importe'),
    sa.ForeignKeyConstraint(['apunte_id'], ['apunte_contable.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['distribucion_apunte_id'], ['distribucion_apunte.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apunte_id', 'contrato_id', name='uq_imputacion_contrato_apunte'),
    sa.UniqueConstraint('distribucion_apunte_id', 'contrato_id', name='uq_imputacion_contrato_distribucion')
    )
    op.create_table('renta_contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('anexo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint('importe >= 0', name='ck_renta_contrato_importe'),
    sa.ForeignKeyConstraint(['anexo_id'], ['anexo_contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contrato_id', 'fecha_desde', name='uq_renta_contrato_fecha_desde')
    )
    op.create_table('factura_destinatario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('nif', sa.Text(), nullable=False),
    sa.CheckConstraint('orden > 0', name='ck_factura_destinatario_orden'),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id', 'orden', name='uq_factura_destinatario_orden')
    )
    op.create_table('factura_linea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id', 'orden', name='uq_factura_linea_orden')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factura_linea')
    op.drop_table('factura_destinatario')
    op.drop_table('renta_contrato')
    op.drop_table('imputacion_contrato')
    op.drop_table('factura')
    op.drop_table('conciliacion')
    op.drop_table('ajuste_renta')
    op.drop_table('revision_renta')
    op.drop_table('movimiento_previsto')
    op.drop_table('distribucion_apunte')
    op.drop_table('contrato_inquilino')
    op.drop_table('anexo_contrato')
    op.drop_table('contrato')
    op.drop_table('apunte_contable')
    op.drop_table('movimiento_bancario')
    op.drop_table('inquilino')
    op.drop_table('inmueble')
    # ### end Alembic commands ###
