"""Añadir facturación

Revision ID: dd64d6ded800
Revises: 34ba5ad163c9
Create Date: 2026-08-20 18:15:44.343294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd64d6ded800'
down_revision: Union[str, Sequence[str], None] = '34ba5ad163c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('numero_secuencia', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.Text(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('periodo', sa.Date(), nullable=False),
    sa.Column('base', sa.Integer(), nullable=False),
    sa.Column('iva_porcentaje', sa.Integer(), nullable=False),
    sa.Column('iva_importe', sa.Integer(), nullable=False),
    sa.Column('retencion_porcentaje', sa.Integer(), nullable=False),
    sa.Column('retencion_importe', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('revision_renta_id', sa.Integer(), nullable=True),
    sa.Column('aviso_revision', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('ruta_pdf', sa.Text(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('EMITIDA', 'ANULADA')", name='ck_factura_estado'),
    sa.CheckConstraint('anio > 0', name='ck_factura_anio'),
    sa.CheckConstraint('base >= 0', name='ck_factura_base'),
    sa.CheckConstraint('iva_importe >= 0', name='ck_factura_iva_importe'),
    sa.CheckConstraint('iva_porcentaje >= 0', name='ck_factura_iva_porcentaje'),
    sa.CheckConstraint('numero_secuencia > 0', name='ck_factura_numero_secuencia'),
    sa.CheckConstraint('retencion_importe >= 0', name='ck_factura_retencion_importe'),
    sa.CheckConstraint('retencion_porcentaje >= 0', name='ck_factura_retencion_porcentaje'),
    sa.CheckConstraint('total >= 0', name='ck_factura_total'),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['revision_renta_id'], ['revision_renta.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_table('factura_linea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.Column('concepto', sa.Text(), nullable=False),
    sa.Column('importe', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('RENTA', 'DIFERENCIA_REVISION', 'REPERCUSION_GASTO')", name='ck_factura_linea_tipo'),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id', 'orden', name='uq_factura_linea_orden')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factura_linea')
    op.drop_table('factura')
    # ### end Alembic commands ###
